apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bbsbnoepi-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bbsbnoepi-dotnet-basic-gitops